"""distance

Revision ID: 6282beecfa6d
Revises: 0ea287c6ef5c
Create Date: 2021-10-27 11:36:54.771525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6282beecfa6d'
down_revision = '0ea287c6ef5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('distance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'distance')
    # ### end Alembic commands ###
